version: "3.9"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: smartuser
      POSTGRES_PASSWORD: smartpass
      POSTGRES_DB: smartdb
      LANG: en_US.UTF-8
      LC_ALL: en_US.UTF-8
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: smart-backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://smartuser:smartpass@db:5432/smartdb

  frontend:
    build: ./frontend
    container_name: smart-frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:80"
    depends_on:
      - backend

  frontend-dev:
    image: node:20-alpine
    container_name: smart-frontend-dev
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_TARGET=http://backend:8000
      - CHOKIDAR_USEPOLLING=1
    command: sh -c "npm ci && npm run dev -- --host 0.0.0.0"
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  pgdata:
