"""add project extra fields and task order

Revision ID: d137cd377a1e
Revises: bf1206ad65ae
Create Date: 2025-10-02 16:42:06.886800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd137cd377a1e'
down_revision: Union[str, Sequence[str], None] = 'bf1206ad65ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('due_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('projects', sa.Column('is_archived', sa.Boolean(), server_default=sa.false(), nullable=False))
    op.add_column('projects', sa.Column('status', sa.String(length=20), server_default='backlog', nullable=False))
    op.add_column('projects', sa.Column('priority', sa.String(length=20), server_default='medium', nullable=False))
    op.add_column('projects', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', now())"), nullable=False))
    op.add_column('tasks', sa.Column('order', sa.Integer(), nullable=True))

    op.alter_column('projects', 'is_archived', server_default=None)
    op.alter_column('projects', 'status', server_default=None)
    op.alter_column('projects', 'priority', server_default=None)
    op.alter_column('projects', 'updated_at', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'order')
    op.drop_column('projects', 'updated_at')
    op.drop_column('projects', 'priority')
    op.drop_column('projects', 'status')
    op.drop_column('projects', 'is_archived')
    op.drop_column('projects', 'due_date')
    # ### end Alembic commands ###

